/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectsmkn8;

import java.awt.Color;
import java.awt.Dialog;
import java.awt.Panel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.security.Security;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Locale;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.Timer;
import javax.swing.border.LineBorder;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author AdiRahmad
 */
public class enkripguru extends javax.swing.JFrame {
    
    

    java.util.Date tglsekarang = new java.util.Date();
    private SimpleDateFormat smpdtfmt = new SimpleDateFormat("dd MMMMMMMMM yyyy", Locale.getDefault());
    private String tanggal = smpdtfmt.format(tglsekarang);
    private int i;

    final void setJam() {
        ActionListener taskPerformer = new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                String nol_jam = "", nol_menit = "", nol_detik = "";
                java.util.Date dateTime = new java.util.Date();
                int nilai_jam = dateTime.getHours();
                int nilai_menit = dateTime.getMinutes();
                int nilai_detik = dateTime.getSeconds();

                if (nilai_jam <= 9) {
                    nol_jam = "0";
                }
                if (nilai_menit <= 9) {
                    nol_menit = "0";
                }
                if (nilai_detik <= 9) {
                    nol_detik = "0";
                }

                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);

                lbljam1.setText(jam + ":" + menit + ":" + detik + "");
            }
        };
        new Timer(1000, taskPerformer).start();
    }

    /**
     * Creates new form SiswaMenu
     */
    public enkripguru() {
        initComponents();
        lbltgl.setText(tanggal);
        setJam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtBrowse = new javax.swing.JTextField();
        txtPass1a = new javax.swing.JPasswordField();
        btnBrowse = new javax.swing.JButton();
        btnEnkrip = new javax.swing.JButton();
        chkTampil = new javax.swing.JCheckBox();
        btnKeluar = new javax.swing.JButton();
        lbltgl = new javax.swing.JLabel();
        lbljam1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectsmkn8/Image/Banner Decrypt.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectsmkn8/Image/guru.png"))); // NOI18N

        jLabel3.setText("Choose File :");

        jLabel5.setText("Password :");

        txtBrowse.setEditable(false);
        txtBrowse.setFocusable(false);

        txtPass1a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPass1aActionPerformed(evt);
            }
        });
        txtPass1a.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPass1aKeyTyped(evt);
            }
        });

        btnBrowse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectsmkn8/Image/arrow-upload-icon (1).png"))); // NOI18N
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        btnEnkrip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectsmkn8/Image/blue-lock-icon.png"))); // NOI18N
        btnEnkrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnkripActionPerformed(evt);
            }
        });

        chkTampil.setText("Show Password");
        chkTampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTampilActionPerformed(evt);
            }
        });

        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectsmkn8/Image/power-icon (1).png"))); // NOI18N
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        lbltgl.setText("tanggal");

        lbljam1.setText("jam");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(10, 10, 10)
                                .addComponent(txtBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(chkTampil, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPass1a, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEnkrip)
                                .addGap(29, 29, 29)
                                .addComponent(btnKeluar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltgl, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lbljam1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(btnBrowse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPass1a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(9, 9, 9)
                .addComponent(chkTampil)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEnkrip)
                            .addComponent(btnKeluar))
                        .addGap(0, 51, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbltgl)
                                .addGap(6, 6, 6)
                                .addComponent(lbljam1)))
                        .addGap(20, 20, 20))))
        );

        setSize(new java.awt.Dimension(626, 372));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chkTampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTampilActionPerformed

        if (chkTampil.isSelected()) {
            txtPass1a.setEchoChar((char) 0);
            
        } else {
            txtPass1a.setEchoChar('*');
            
        }
// TODO add your handling code here:
    }//GEN-LAST:event_chkTampilActionPerformed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed

        JFileChooser Filter = new JFileChooser();
        Filter.setCurrentDirectory(new File(System.getProperty("user.home")));
        Filter.setFileSelectionMode(JFileChooser.FILES_ONLY);
        Filter.setAcceptAllFileFilterUsed(true);
        Filter.addChoosableFileFilter(new FileNameExtensionFilter("PDF file", "pdf"));
        Filter.addChoosableFileFilter(new FileNameExtensionFilter("Office Dokumen", "docx", "xlsx", "pptx", "doc", "ppt", "xls"));
        Filter.addChoosableFileFilter(new FileNameExtensionFilter("Gambar", "jpg", "png", "gif", "bmp"));

        int Hasil = Filter.showOpenDialog(this);
        if (Hasil == JFileChooser.APPROVE_OPTION) {
            File Sourcenya = Filter.getSelectedFile();
            txtBrowse.setText(Sourcenya.toString());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBrowseActionPerformed

    void Bersih (){
    txtBrowse.setText("");
    txtPass1a.setText("");
   }
    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
int Pilih = JOptionPane.showConfirmDialog(null, "Apakah anda ingin keluar dari enkripsi ?","Peringatan",JOptionPane.OK_CANCEL_OPTION);
    if (Pilih == JOptionPane.OK_OPTION){
    dispose();
        }else if(Pilih == JOptionPane.CANCEL_OPTION){
            Bersih();
        } 
    
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKeluarActionPerformed

    void SimpanKunci() {
    
    String Text, judul;
        Text = txtPass1a.getText();
        judul = txtBrowse.getText();
        File log = new File(judul + ".txt");
        if (log.exists() == false) {
            JFileChooser chooser = new JFileChooser();
            chooser.setCurrentDirectory(new File("D:\\"));
            int retrival = chooser.showSaveDialog(null);
            if (retrival == JFileChooser.APPROVE_OPTION)
            {
                try(FileWriter fw = new FileWriter(chooser.getSelectedFile()+".txt"))
                {
                    fw.write(Text.toString());
                    JOptionPane.showMessageDialog(null, "Berhasil membuat Kunci ");
                }
                catch (Exception ex)
                {
                    ex.printStackTrace();
                }
            }
        }
    }             
    
    private void btnEnkripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnkripActionPerformed
        
        String keydefault = "1";
        String PassKosongA = null;
        File file = new File(txtBrowse.getText());
        String pass1 = txtPass1a.getText();
        int i;
        
        
        if (pass1.length()<=32){
            PassKosongA =  pass1;
            for (i = 0 ; i <= 32 - pass1.length() ;i++ ){
        
               PassKosongA = PassKosongA + keydefault;
            }
            Arrays.toString(PassKosongA.getBytes());
                   
        }
        
        
        
        if (txtBrowse.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Silahkan Pilih file anda terlebih dahulu","Perhatian",JOptionPane.WARNING_MESSAGE);}
         if (txtPass1a.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Silahkan Masukkan Password anda","Perhatian",JOptionPane.WARNING_MESSAGE);
         }else{
        try {
            byte[] myByte = new byte[(int) file.length()];
            try (FileInputStream bos = new FileInputStream(file.getAbsolutePath())) {
                bos.read(myByte, 0, (int) file.length());
            }
            AES aes = new AES();
            aes.setKey(PassKosongA);
            String encryptedString = aes.Encrypt(AES.static_byteArrayToString(myByte));
            byte[] encryptedByte = AES.static_stringToByteArray(encryptedString);
            String filePathWithoutExt = file.getAbsolutePath().substring(0, file.getAbsolutePath().lastIndexOf("."));
            try (FileOutputStream encryptedFile = new FileOutputStream(filePathWithoutExt + "-File Terenkripsi" + file.getAbsolutePath().substring(file.getAbsolutePath().lastIndexOf("."), file.getAbsolutePath().length()))) {
                encryptedFile.write(encryptedByte);
            }
           
            JOptionPane.showMessageDialog(null, " Data Berhasil Terenkripsi \n Pilih Dimana Anda ingin menyimpan Kunci !" );
            SimpanKunci();
             Bersih();
            
             
        } catch (IOException e) {
        }
                
    }
        
    }//GEN-LAST:event_btnEnkripActionPerformed

    private void txtPass1aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPass1aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPass1aActionPerformed

    private void txtPass1aKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPass1aKeyTyped
if ( txtPass1a.getText().length() == 32 ) {
        evt.consume();
    }
        
// TODO add your handling code here:
    }//GEN-LAST:event_txtPass1aKeyTyped

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(enkripguru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(enkripguru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(enkripguru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(enkripguru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new enkripguru().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnEnkrip;
    private javax.swing.JButton btnKeluar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkTampil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbljam1;
    private javax.swing.JLabel lbltgl;
    private javax.swing.JTextField txtBrowse;
    private javax.swing.JPasswordField txtPass1a;
    // End of variables declaration//GEN-END:variables
}
